/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Cuenta;
import modelo.CuentaJunior;
import modelo.CuentaPremium;

/**
 *
 * @author luiscobian
 */
public class AgregarCuenta extends javax.swing.JDialog {

    
    int tipoCuenta; 
    
    /**
     * Creates new form AgregarCuenta
     */
    public AgregarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblError.setVisible(false);
        visualizarEdad(false);
        tipoCuenta = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtInicialCuenta = new javax.swing.JTextField();
        btnCrearCuenta = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jtEdad = new javax.swing.JTextField();
        lblEdad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoCuenta = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(591, 520));

        jPanel1.setBackground(new java.awt.Color(153, 200, 214));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Agregar Cuenta");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/img/banco.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Titular de la cuenta:");

        txtTitular.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Inicial de la cuenta:");

        txtInicialCuenta.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        txtInicialCuenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInicialCuenta.setText("0");
        txtInicialCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInicialCuentaKeyPressed(evt);
            }
        });

        btnCrearCuenta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 51, 51));
        lblError.setText("Valor inválido");

        jtEdad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jtEdad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtEdad.setText("0");
        jtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtEdadKeyPressed(evt);
            }
        });

        lblEdad.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(102, 102, 102));
        lblEdad.setText("Edad");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Tipo de cuenta");

        cmbTipoCuenta.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        cmbTipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una cuenta", "JUNIOR", "PREMIUM" }));
        cmbTipoCuenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipoCuentaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTipoCuenta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtTitular, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblError)
                                    .addComponent(txtInicialCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEdad)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jtEdad, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEdad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInicialCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError)
                .addGap(18, 18, 18)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        // TODO add your handling code here:
        double valorInicialCuenta = 0;
          try{
                valorInicialCuenta = Double.parseDouble
                                       (txtInicialCuenta.getText());                
            }catch(NumberFormatException e){
                lblError.setVisible(true);
                return;
            }
        if(valorInicialCuenta<0){
            lblError.setVisible(true);
            return; 
        }  
        String titular = txtTitular.getText().trim(); 
        if(titular.isEmpty())
        {
            lblError.setVisible(true);
            return; 
        }
        Cuenta cuenta = null; 
        switch(tipoCuenta){
            case 1: 
                int edad = Integer.parseInt(jtEdad.getText()); 
                System.out.println("Edad: " + edad);
                if(edad <1 || edad>18){
                    lblError.setVisible(true);
                    return;
                }
                else {
                    cuenta = new CuentaJunior(titular, valorInicialCuenta, edad);                
                }
                break; 
            case 2:
                cuenta = new CuentaPremium(titular, valorInicialCuenta);
                break; 
            default: 
                lblError.setVisible(true);
                return; 
        }
        this.dispose();                
        DetalleCuenta dc = new DetalleCuenta
                             (null,true,cuenta);
        dc.setVisible(true);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void txtInicialCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInicialCuentaKeyPressed
        // TODO add your handling code here:
        lblError.setVisible(false);
    }//GEN-LAST:event_txtInicialCuentaKeyPressed

    private void jtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtEdadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEdadKeyPressed

    private void cmbTipoCuentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipoCuentaItemStateChanged
        // TODO add your handling code here:
        lblError.setVisible(false);
        int indiceSeleccionado = cmbTipoCuenta.getSelectedIndex();        
        System.out.println("Indice: " + indiceSeleccionado);
        switch(indiceSeleccionado){
            case 1: 
                visualizarEdad(true);
                tipoCuenta = 1; 
                break; 
            case 2: 
                visualizarEdad(false);
                tipoCuenta = 2; 
                break; 
            default:
                tipoCuenta = -1; 
        }
        
    }//GEN-LAST:event_cmbTipoCuentaItemStateChanged
   

    private void visualizarEdad(boolean mostrar) {
        lblEdad.setVisible(mostrar);
        jtEdad.setVisible(mostrar);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JComboBox<String> cmbTipoCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtEdad;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtInicialCuenta;
    private javax.swing.JTextField txtTitular;
    // End of variables declaration//GEN-END:variables
}
